### PR TITLE
Add MIT License

### LINKED ISSUE #1: Missing license
Hi Floris

`byar` doesn't specify a license, which [prevents is to be used legally by third parties][1]. If it's an oversight, could you provide a license.

Thanks

[1]: https://choosealicense.com/no-permission/

### PR DESCRIPTION
**Pull request by florish**
Closes #1

### CODE REVIEW

**Comment by florish** [comment]
@artm I've invited you to collaborate on this repository. After you've accepted, I'll assign you for review and merge. Feel free to squash the commits before merging!

**Comment by artm** [comment]
:+1:

**Comment by artm** [comment]
Could you also [reference the license in the gemspec][1], and bump the gem version number?

[1]: https://guides.rubygems.org/specification-reference/#license=

**Comment by florish** [comment]
> Could you also [reference the license in the gemspec](https://guides.rubygems.org/specification-reference/#license=), and bump the gem version number?

Yes, will do in a minute and will assign you afterwards!

**Comment by florish** [comment]
@artm Changes made:

* MIT License reference added to gemspec
* Version bumped to 1.0.0 (new license feels like a major upgrade, and to be honest, `byar` has been out of beta for a while now, hasn't it? 😄 )
* CHANGELOG.md added to clarify changes made just now and over the past years

**Comment by artm** [comment]
LGTM

**Pull request merged**
